### ISSUE TITLE
Is button glow planned?

### ISSUE THREAD

**Issue by Tamim468** [ALTaleX531/OpenGlass#5]
This looks very promising, I heard nostalgia 09 has switched to this for reasons with also using awm too.
![image](https://github.com/ALTaleX531/OpenGlass/assets/79998020/e3602177-a3d4-4007-9b12-d22ec61975db)
![image](https://github.com/ALTaleX531/OpenGlass/assets/79998020/45f87206-b5d4-42a8-8cec-811940a13536)

Unfortunately since button glow is not available in openglass and awm, it results in windows 10 to 7 setups losing button glow while they move to openglass & awm. it makes it a bit more bland and it would be disappointing for the windows modding community to lose button glow especially people finding out that n07 and n09 will no longer include button glow as a result of this. 
![image](https://github.com/ALTaleX531/OpenGlass/assets/79998020/2c111eb5-98a3-40b5-acc2-2449277097fc)

I can hope that you plan to add button glow to fix this issue. Would be greatly appreciated :)

**Comment by ALTaleX531** [comment]
At the moment I don't plan to implement button glow. Many people complain that dwmbg is very unstable, this is because the framework I wrote before was very buggy, this is one of the reasons why openglass was created to replace acryliceverywhere, in the future dwmbg will be as stable as openglass. 

These two projects were created for different reasons. openglass only provides basic functionality but its code is highly customizable. The extra features that I don't have time to maintain will be put into dwmbg and maintained by maplespe. I developed openglass just for fun, I don't want it to take over my life like bigmuscle.

For now openglass is considered complete and will only receive bug fixes not new features. I'm working on how to implement glass in a fully glass8 way and without relying on dcomp. Here's the progress I've made so far, since I'm not a good programmer, I just successfully messed up my desktop :)
![image](https://github.com/ALTaleX531/OpenGlass/assets/105535231/db95dbaa-9ea8-4bea-878f-6e51663b3c2f)

**Comment by aubymori** [comment]
\>dcomp-less openglass
![image](https://github.com/ALTaleX531/OpenGlass/assets/44238627/383b97d5-7535-4cd2-a6e0-b36ca8cd2269)

**Comment by windowsxp3790** [comment]
> > > dcomp-less openglass ![image](https://private-user-images.githubusercontent.com/44238627/342146117-383b97d5-7535-4cd2-a6e0-b36ca8cd2269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxODQ5MjksIm5iZiI6MTcxOTE4NDYyOSwicGF0aCI6Ii80NDIzODYyNy8zNDIxNDYxMTctMzgzYjk3ZDUtNzUzNS00Y2QyLWE2ZTAtYjM2Y2E4Y2QyMjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDIzMTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNjI3MTJkMDI5MjkzZDg4YzQ0YWJiNjEyNDFjYjEyY2M5ZmM5YjIzMzU5ZDA0NzY3MTZlMDhmMmI0NmQyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dfJ3n9quHrBveH9JEEEYq-5TaG-J2ESEh0sRgZ0dkfY)
> 
> Hello bro

Hello vro

**Comment by ALTaleX531** [comment]
I just released a beta version of OpenGlass Legacy if any of you want to give it a try.

**Comment by aubymori** [comment]
> I just released a beta version of OpenGlass Legacy if any of you want to give it a try.

It's *amazing*. Any performance issues I had with DWMBG and earlier builds of OpenGlass are basically gone. There is an issue where switching between windows sometimes causes the blur to go away temporarily. Is that the issue with AccentState 3 you mentioned, or should I open an issue about it?

**Comment by aubymori** [comment]
Also, it told me that my system wasn't supported, but worked fine. Weird stuff. If you want to know, I'm running with uDWM.dll version 10.0.19041.3758.

**Comment by ALTaleX531** [comment]
@aubymori 
> There is an issue where switching between windows sometimes causes the blur to go away temporarily.

It's not the AccentState of 3 that I'm talking about, this looks like another bug, you can post it to [discussion](https://github.com/ALTaleX531/OpenGlass/discussions/9) and it would be nice to include a video of how it was reproduced.
> Also, it told me that my system wasn't supported, but worked fine. Weird stuff. If you want to know, I'm running with uDWM.dll version 10.0.19041.3758.

![image](https://github.com/ALTaleX531/OpenGlass/assets/105535231/b45d2a39-0bc1-4cae-922b-2ec2a27e5763)
This is probably because I limited the build number to 22H2. But actually, it should work fine for 2004-22H2, since the DWM is almost unchanged for those versions.

**Comment by aubymori** [comment]
> ![image](https://private-user-images.githubusercontent.com/105535231/344241411-b45d2a39-0bc1-4cae-922b-2ec2a27e5763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTE4NjEsIm5iZiI6MTcxOTU5MTU2MSwicGF0aCI6Ii8xMDU1MzUyMzEvMzQ0MjQxNDExLWI0NWQyYTM5LTBiYzEtNGNhZS05MjJiLTJlYzJhMjdlNTc2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxNjE5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmRkYzQyZWY5ZTFmYWVmOGJiMzQ0YmIwNWMxNDkxM2IyMDk3MzI2OTAzN2Y1MWRmY2EwNjk2YjJiZWQ0MmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sWYOftKiCDeH6z9e32zRneai6MJ93ZmV6vY1CuCP7NI) This is probably because I limited the build number to 22H2. But actually, it should work fine for 2004-22H2, since the DWM is almost unchanged for those versions.

Oh yeah, you should change that to include 21H2. Should mention that system files still have their build number as 19041, because 19042-19045 are all fake build numbers reported by Windows and the real build number is still technically 19041, but that's a whole other can of worms.
